/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\computer.gltf --transform 
Files: .\public\models\computer.gltf [10.35KB] > C:\Users\ceili\source\repos\Portfolio\portfolio.client\computer-transformed.glb [17.53KB] (-69%)
*/
import React from "react"
import { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { animated } from "@react-spring/three"
import { lerp } from "three/src/math/MathUtils"

export default function ComputerModel(props) {
  const { nodes, materials } = useGLTF("/models/computer-transformed.glb")
  const meshRef = useRef()

  useFrame(() => {
    meshRef.current.rotation.y += 0.005
  })

  return (
    <group {...props} position={[0, 0, 0]} dispose={null}>
      <group position={[-5, 0, -3]} dispose={null} ref={meshRef}>
        <animated.mesh
          geometry={nodes.Base_Computer_0.geometry}
          material={materials.Computer}
          scale={0.09}
          position={[0, 0, 0]}
          rotation={[0.15, 300, 0]}
        >
          <meshPhysicalMaterial color="hotpink" />
        </animated.mesh>
      </group>
    </group>
  )
}

useGLTF.preload("/models/computer-transformed.glb")
